server {
    listen 80;
    server_name uploads.uptunnel.dev;

    client_max_body_size 32m;

    location /health {
        proxy_pass http://bot:8000/health;
    }

    location /d/ {
        proxy_pass http://bot:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /_protected_downloads/ {
        internal;
        alias /downloads/;
        add_header Content-Disposition "attachment";
    }
}
