server {
    listen 80;
    server_name uploads.uptunnel.dev;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name uploads.uptunnel.dev;

    ssl_certificate /etc/letsencrypt/live/uploads.uptunnel.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/uploads.uptunnel.dev/privkey.pem;

    client_max_body_size 32m;

    location / {
        proxy_pass http://bot:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /_protected_downloads/ {
        internal;
        alias /downloads/;
    }
}
